# dynamic_title = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#9a929d"
blue = "#8E8EAF"
cyan = "#A7A3C8"
green = "#7486AA"
magenta = "#A391A9"
red = "#6E889E"
white = "#ddd1e1"
yellow = "#57A7C0"

[colors.cursor]
cursor = "#ddd1e1"
text = "#0c121d"

[colors.normal]
black = "#0c121d"
blue = "#8E8EAF"
cyan = "#A7A3C8"
green = "#7486AA"
magenta = "#A391A9"
red = "#6E889E"
white = "#ddd1e1"
yellow = "#57A7C0"

[colors.primary]
background = "#0c121d"
foreground = "#ddd1e1"

[cursor]
style = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 5000

[window]
dynamic_padding = false
opacity = 0.85
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
